name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t devsecops-app .

    - name: Scan with Trivy
  run: |
    trivy image \
      --severity HIGH,CRITICAL \
      --exit-code 1 \
      devsecops-app
